### ISSUE TITLE
Log distribution

### ISSUE THREAD

**Issue by franky47** [47ng/actions-clever-cloud#178]
Provide a way to pass deployment logs to other actions. This can be:
- Via an output variable:
```yaml
- uses: 47ng/actions-clever-cloud@version
  id: deploy
  with:
    logs:
      output: true
- run: echo ${{ steps.deploy.outputs.logs }}
```
- Via the filesystem:
```yaml
- uses: 47ng/actions-clever-cloud@version
  with:
    logs:
      file: ./path/to/file.log # resolved as relative to repository root
```
Or a combination of those options.

Because logs are printed to the standard output by the Clever Tools CLI, a way to hide them if they contain sensitive data could also be useful:
```yaml
- uses: 47ng/actions-clever-cloud@version
  with:
    logs:
      stdout: false
```
