### ISSUE TITLE
Deployment says successful when it has stopped

### ISSUE THREAD

**Issue by pYassine** [47ng/actions-clever-cloud#204]
For 1 week, the deployment indicates that it is successful while when we open the logs we come across the following error:

"Error: Cannot read properties of null (reading 'slice')"

![Capture d’écran 2023-05-15 à 16 26 00](https://github.com/47ng/actions-clever-cloud/assets/11486845/f0f6e0c5-7adb-4fef-8e33-782ba016fd3c)

**Comment by franky47** [comment]
Fixed in [v2.1.1](https://github.com/47ng/actions-clever-cloud/releases/tag/v2.1.1)

Pinning info:
```yml
# Consume via Git:
- uses: 47ng/actions-clever-cloud@e4177599d4c6c9a552a6a4d998f94ba263578cd4

# Consume via Docker (preferred):
- uses: docker://ghcr.io/47ng/actions-clever-cloud@sha256:c374d7bc5e669d01d1d76eaa17bc9645994825f5d3928b2accf1117a8b310029
```
