### ISSUE TITLE
Deployment action hangs forever

### ISSUE THREAD

**Issue by sneko** [47ng/actions-clever-cloud#206]
Hi,

For whatever reason, randomly the step of deploying can hangs forever **whereas the deployment is effective on Clever Cloud**. Does anyone has encountered this issue?

I'm using:
```yaml
      - name: Deploy to Clever Cloud
        uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: ${{ env.CLEVER_APP_ID }}
          force: true
          quiet: true # disable copying into GitHub Actions all logs from Clever Cloud
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
```

I have to cancel my run after X hours to free my pipeline. Note in a normal situation it takes around 5 minutes to deploy.

<img width="1277" alt="image" src="https://github.com/47ng/actions-clever-cloud/assets/8195958/4df49086-6dd7-40d5-8a55-a04d87cfe7d2">

A solution to mitigate freezing the pipeline would be to add something like `timeout-minutes: 15` to the step so it warns us to check the deployment has worked or not.

Thank you,

**Comment by franky47** [comment]
There is a [timeout option](https://github.com/47ng/actions-clever-cloud?tab=readme-ov-file#deployment-timeout), although I've been seeing successful deployments failing to mark the step as complete and keeping running until that timeout occurs, I'll have to investigate.

**Comment by franky47** [comment]
I have published v2.0.0 with the latest clever-tools, which could help with this issue. Could you give it a try please?

**Comment by franky47** [comment]
Fixed in [v2.1.1](https://github.com/47ng/actions-clever-cloud/releases/tag/v2.1.1)

Pinning info:
```yml
# Consume via Git:
- uses: 47ng/actions-clever-cloud@e4177599d4c6c9a552a6a4d998f94ba263578cd4

# Consume via Docker (preferred):
- uses: docker://ghcr.io/47ng/actions-clever-cloud@sha256:c374d7bc5e669d01d1d76eaa17bc9645994825f5d3928b2accf1117a8b310029
```
