### ISSUE TITLE
ENAMETOOLONG: name too long, stat

### ISSUE THREAD

**Issue by darkterra** [47ng/actions-clever-cloud#85]
Hello,
I try to deploy on Clever Cloud from GitHub Actions, and I have this wird error from this action :

```
Run 47ng/actions-clever-cloud@v1
  with:
    appID: ***
  env:
    CLEVER_TOKEN: ***
    CLEVER_SECRET: ***
/usr/bin/docker run --name ngactionsclevercloudv100_5891b3 --label 1e5c35 --workdir /github/workspace --rm -e CLEVER_TOKEN -e CLEVER_SECRET -e INPUT_APPID -e INPUT_ALIAS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/assetregister-newclient/assetregister-newclient":"/github/workspace" 47ng/actions-clever-cloud:v1.0.0
/action/node_modules/.bin/clever login --token *** --secret ***
/action/node_modules/.bin/clever link *** --alias ***
Your application has been successfully linked!
/action/node_modules/.bin/clever deploy --alias ***
Error:  ENAMETOOLONG: name too long, stat '../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../.git'
Error: The process '/action/node_modules/.bin/clever' failed with exit code 1
```

There is the job :
```
 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Clever Cloud
      uses: 47ng/actions-clever-cloud@v1
      with:
        appID: ${{ secrets.APP_ID }}
      env: 
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
```

Some one can tell me what is my mistake ?

**Comment by franky47** [comment]
The documentation states that you need to check out your repository:
```
  # This action requires an unshallow working copy,
  # so the following prerequisites are necessary:
  - uses: actions/checkout@v2
  - run: git fetch --prune --unshallow
```

For the story, what's going on here is that the clever-tools can't find the `.git` directory, so tries to walk up the tree until it bails when the pathname is too long.

**Comment by darkterra** [comment]
Hello franky47,

Is it possible to close the issue once I have validated that your answer solves my problem?

For information, I had not shown the entire file, and I had followed the documentation well by putting the right options in the "git fetch",but I did not think that the build part had an impact (I am starting in Actions):
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Install Node.js v13
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm i
    - run: NODE_ENV=production CI=false npm run build
      env:
        CI: false
        NODE_ENV: production
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Clever Cloud
      uses: 47ng/actions-clever-cloud@v1
      with:
        appID: ${{ secrets.APP_ID }}
      env: 
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
```

From what I understand, I am forced to use artifacts if I want to separate the "build" phase and the "deploy" phase.

However, is it possible to deploy differently or force the deploy without .git?
Because I need to build a React app and I won't store the build result in a Git repo
